# Generated by Django 5.0.4 on 2024-09-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('damageID', models.AutoField(primary_key=True, serialize=False)),
                ('damageObservedDate', models.DateField()),
                ('damageOccuredDate', models.DateField(blank=True, null=True)),
                ('damageType', models.CharField(max_length=100)),
                ('damageSeverity', models.SmallIntegerField(choices=[(0, 'Minor'), (1, 'Moderate'), (2, 'Severe'), (3, 'Critical')], default=0)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('damageImage', models.ImageField(blank=True, default='images/asset_images/defaultImage.jpg', upload_to='damageImages/')),
                ('scheduledMaintenanceDate', models.DateField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenanceID', models.AutoField(primary_key=True, serialize=False)),
                ('completionDate', models.DateField()),
                ('maintenaceType', models.PositiveIntegerField(choices=[(0, 'General'), (1, 'Scehduled Service'), (2, 'Inspection'), (3, 'Repair')], default=0)),
                ('maintenanceLocation', models.CharField(max_length=100)),
                ('maintenanceTasksCompleted', models.CharField(max_length=255)),
                ('Cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Notes', models.CharField(max_length=255)),
                ('kmsBeforeNextService', models.IntegerField()),
                ('dateOfNextService', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
