# Generated by Django 5.0.4 on 2024-09-24 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetMaintenance', '0001_initial'),
        ('assetManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damage',
            name='assetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='assetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.asset'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenanceConductedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='repairsCompleted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetMaintenance.damage'),
        ),
    ]
