# Generated by Django 5.0.4 on 2025-04-01 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FarmAcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('geographicLocation', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('validLocation', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('scope', models.JSONField(default=dict)),
                ('col', models.IntegerField(default=1)),
                ('row', models.IntegerField(default=1)),
                ('sizex', models.IntegerField(default=1)),
                ('sizey', models.IntegerField(default=1)),
                ('saved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastTable',
            fields=[
                ('Forecast_ID', models.AutoField(primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=50)),
                ('weatherDescription', models.CharField(max_length=255)),
                ('temperature', models.FloatField()),
                ('temperatureMin', models.FloatField()),
                ('temperatureMax', models.FloatField()),
                ('feelsLike', models.FloatField()),
                ('humidity', models.FloatField()),
                ('cloudCoverage', models.FloatField()),
                ('sunrise', models.IntegerField(null=True)),
                ('sunset', models.IntegerField(null=True)),
                ('weatherIcon', models.CharField()),
                ('forecastOffsetHours', models.IntegerField()),
                ('geographicLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.location')),
            ],
        ),
        migrations.CreateModel(
            name='RetrievalTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeatherRetrieval', models.DateTimeField(null=True)),
                ('forecastRetrieval', models.DateTimeField(null=True)),
                ('geographicLocation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashboard.location')),
            ],
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_data', models.JSONField(default=list)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='FarmAcc.farminfo')),
                ('widgets', models.ManyToManyField(to='Dashboard.widget')),
            ],
        ),
    ]
