# Generated by Django 5.0.4 on 2025-04-10 04:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('satellite_name', models.CharField(default='Sentinel-2', max_length=100)),
                ('tile_id', models.CharField(max_length=100)),
                ('capture_date', models.DateField()),
                ('cloud_cover', models.FloatField()),
                ('image_url', models.URLField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('aoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maptiles.aoi')),
            ],
            options={
                'unique_together': {('tile_id', 'capture_date')},
            },
        ),
        migrations.CreateModel(
            name='NDVIMap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ndvi_raster_url', models.URLField()),
                ('ndvi_thumbnail_url', models.URLField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('satellite_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_map', to='maptiles.satelliteimage')),
            ],
        ),
    ]
