# Generated by Django 5.0.4 on 2025-04-01 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetExpenses', '0002_initial'),
        ('assetManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='assetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.asset'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expenseLodgedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
