# Generated by Django 5.0.4 on 2024-09-24 09:08

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FarmAcc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('timeStamp', models.DateTimeField(default=datetime.datetime.now)),
                ('isCompleted', models.BooleanField(default=False)),
                ('isArchived', models.BooleanField(default=False)),
                ('isDeleted', models.BooleanField(default=False)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Blocked'), (3, 'Review'), (4, 'Complete'), (5, 'Archived')], default=0)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High'), (3, 'Urgent')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Kanban',
            fields=[
                ('kanbanID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('deleted', models.BooleanField(default=False)),
                ('farmID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FarmAcc.farminfo')),
            ],
        ),
        migrations.CreateModel(
            name='KanbanContents',
            fields=[
                ('kanbanContentsID', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('kanbanID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.kanban')),
            ],
        ),
    ]
