# Generated by Django 5.0.4 on 2024-10-09 08:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assetManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('logID', models.AutoField(primary_key=True, serialize=False)),
                ('startDateTime', models.DateTimeField(default=datetime.datetime.now)),
                ('endDateTime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=64)),
                ('notes', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('assetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.asset')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('metricID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('assetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetManagement.asset')),
            ],
        ),
        migrations.CreateModel(
            name='OperationLogMetric',
            fields=[
                ('logMetricID', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('logID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetOperation.operationlog')),
                ('metricID', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='assetOperation.performancemetric')),
            ],
        ),
    ]
